homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 25
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include_dir_merge_named customizations

  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.0.0/16
      allow_bypass_login: true
    - type: legacy_api_password
      api_password: !secret api_password

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  server_port: 8123
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123
  #ssl_certificate: /home/pi/ssl/chain
  #ssl_key: /home/pi/ssl/key

zone:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  radius: 30
  icon: mdi:home

# Checks for available updates
updater:
  reporting: no

# Discover some devices automatically
discovery:
  ignore:
    - philips_hue
    - google_cast

# Prometheus
prometheus:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google_translate

# Components:
group: !include groups.yaml

light: !include lights.yaml

device_tracker: !include device_tracker.yaml

emulated_hue: !include emulated_hue.yaml

media_player: !include media_player.yaml

scene: !include_dir_list scenes

wake_on_lan:
