- platform: tomato
  host: 192.168.1.1
  username: !secret netgear_user
  password: !secret netgear_pass
  http_id: TID48cc3e8ac532027f
  interval_seconds: 60
  consider_home: 300
  track_new_devices: true
