version: "3.5"

networks: 
  home:
    driver: macvlan
    driver_opts: 
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.1.0/24

services:
  traefik:
    image: traefik:1.7
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./traefik/traefik.toml:/traefik.toml"
      - "./traefik/acme.json:/acme.json"
    labels:
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:lab.javydekoning.com"  
  
  portainer:
    container_name: portainer
    image: portainer/portainer:latest
    restart: unless-stopped
    ports: 
      - "9000:9000"
    labels:
      - "traefik.port=9000"
      - "traefik.frontend.rule=Host:portainer.lab.javydekoning.com"
    volumes:
      - ./portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock

  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:latest
    restart: unless-stopped
    networks:
      home:
        ipv4_address: 192.168.1.200
    ports: 
      - "80:8123"   #web frontend
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - ./homeassistant/config:/config

  rutorrent:
    container_name: rutorrent
    image: diameter/rtorrent-rutorrent:latest
    restart: unless-stopped
    ports: 
      - "8080:8080" 
      - "49160:49160/udp" 
      - "49161:49161"
    labels:
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:rutorrent.lab.javydekoning.com"  
    volumes: 
      - ./downloads:/downloads 
    dns:
      - 1.1.1.1

  nfs:
    container_name: nfs
    image: fuzzle/docker-nfs-server:latest
    restart: unless-stopped
    ports:
      - "111:111"
      - "111:111/udp"
      - "2049:2049"
      - "2029:2049/udp"
      - "32765:32765"
      - "32765:32765/udp"
      - "32766:32766"
      - "32766:32766/udp"
      - "32767:32767"
      - "32767:32767/udp"
    environment:
      - 'NFS_EXPORT_DIR_1=/nfs'
      - 'NFS_EXPORT_DOMAIN_1=*'
      - 'NFS_EXPORT_OPTIONS_1=ro,insecure,no_subtree_check,no_root_squash,fsid=1'
    volumes:
      - ./downloads:/nfs
    privileged: true
    labels: 
      - "traefik.enable=false"

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    ports:
      - "8989:8989"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./sonarrconfig:/config
      - ./downloads:/downloads
    labels:
      - "traefik.port=8989"
      - "traefik.frontend.rule=Host:sonarr.lab.javydekoning.com"  
    dns: 1.1.1.1

  emby:
    image: emby/embyserver:latest
    container_name: emby
    ports:
      - 8096:8096
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./embyserver:/config
      - ./downloads:/downloads
    labels:
      - "traefik.port=8096"
      - "traefik.frontend.rule=Host:emby.lab.javydekoning.com"   
      - AUTO_UPDATES_ON=true
    dns: 1.1.1.1

  watchtower:
    container_name: watchtower
    restart: always
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 10 * * *" --cleanup
    dns: 1.1.1.1

  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - PLEX_CLAIM=claim-5atxMAs6oBnGYUuCysgq
      - ADVERTISE_IP=http://192.168.1.9:32400/
      - TZ=Europe/Amsterdam
    volumes:
      - /srv/docker/plex:/config
      - /srv/docker/downloads/movies:/data/movies
      - /srv/docker/downloads/tv:/data/tv

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      home:
        ipv4_address: 192.168.1.201
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Europe/Amsterdam'
      WEBPASSWORD: 'NotMyPassword'
      VIRTUAL_HOST: 'pihole.lab.javydekoning.com'
      ServerIP: '192.168.1.201'
    volumes:
       - './etc-pihole/:/etc/pihole/'
       - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  smokeping:
    image: linuxserver/smokeping
    container_name: smokeping
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /srv/docker/smokeping/config:/config
      - /srv/docker/smokeping/data:/data
    ports:
      - 8200:80
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 8.8.8.8
