version: "3.7"

networks:
  base_backend:
    external: true

services:
  smokeping:
    image: linuxserver/smokeping
    container_name: smokeping
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./smokeping/config:/config
      - ./smokeping/data:/data
    ports:
      - 8200:80
    restart: unless-stopped
    networks: base_backend
    dns:
      - 1.1.1.1
      - 8.8.8.8