# uncomment for debugging
#logLevel = "DEBUG"

defaultEntryPoints = ["http","https"]

[web]
  address = ":8080"

[entryPoints]
  [entryPoints.http]
    address = ":80"
    whitelistSourceRange = ["192.168.1.0/24","192.168.3.0/24"]
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]

[acme]
  email = "info@javydekoning.com"
  storage = "acme.json"
  entryPoint = "https"
  onHostRule = true
  [acme.httpChallenge]
    entryPoint = "http"

[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "dockerdemo.javydekoning.com"
  watch = true

