version: "3.7"

networks:
  base_homelan:
    external: true
  base_backend:
    external: true

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      base_homelan:
        ipv4_address: 192.168.1.201
    # ports:
    #   - "53:53/tcp"
    #   - "53:53/udp"
    #   - "80:80/tcp"
    #   - "443:443/tcp"
    environment:
      TZ: 'Europe/Amsterdam'
      WEBPASSWORD: 'NotMyPassword'
      VIRTUAL_HOST: 'pihole.lab.javydekoning.com'
      ServerIP: '192.168.1.201'
    volumes:
       - './etc-pihole/:/etc/pihole/'
       - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"