version: "3.7"

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  portainer:
    container_name: portainer
    image: portainer/portainer:latest
    restart: unless-stopped
    labels:
      - traefik.http.services.portainer.loadbalancer.server.port=9000
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.lab.javydekoning.com`)"
      - "traefik.http.routers.portainer.entrypoints=web"    
    volumes:
      - ./portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend

  watchtower:
    container_name: watchtower
    restart: always
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 10 * * *" --cleanup
    dns: 1.1.1.1

  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    networks:
      - frontend
      - backend
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.lab.javydekoning.com`)"
      - "traefik.http.routers.traefik.entrypoints=web"          

  whoami:
    image: "containous/whoami"
    container_name: "simple-service"
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.lab.javydekoning.com`)"
      - "traefik.http.routers.whoami.entrypoints=web"    